<?php
echo "<pre>";
// print_r($data);
echo "</pre>";
?>
<div class="h-screen w-screen flex justify-center items-center">
    <form action="#" method="post" class="p-3">
        <a href="delete/<?php echo $data->id; ?>"><i class="fa fa-trash"></i></a>
        <label for="image" class="mt-2">
            <p><i class="fa fa-image bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> image</p>
            <input type="text" value="<?php echo $data->blog_image; ?>" name="image" id="image" placeholder="image" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="title" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> title</p>
            <input type="text" value="<?php echo $data->blog_title; ?>" name="title" id="title" placeholder="title" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="tags" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> tags</p>
            <input type="text" value="<?php echo $data->blog_tags; ?>" name="tags" id="tags" placeholder="tags" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="content" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> content</p>
            <textarea rows="10" name="content" id="content" placeholder="content" class="border-2 border-stone-700 rounded-sm mt-2 w-full" required><?php echo $data->blog_content; ?>
        </textarea>
        </label>
        <label for="submit" class="w-full my-4">
            <input type="submit" value="Update" name="submit" id="name" class="w-full p-2 rounded-sm shadow-md cursor-pointer text-white bg-gradient-to-r from-pink-500 to-red-600 ">
        </label>
    </form>
</div>