<?php

use Phalcon\Session\Manager;
use Phalcon\Session\Adapter\Stream;

$session = new Manager();
$files = new Stream(
    [
        'savePath' => '/tmp',
    ]
);
$session->setAdapter($files)->start();
// print_r($session->get("user"));
?>
<!-- including navbar 🛬 -->
<nav class="p-3 shadow-lg fixed w-full bg-gradient-to-r from-pink-500 to-red-600 text-white">
    <div class="flex justify-between flex-col sm:flex-row items-">
        <ul class="navbar  list-none flex justify-center items- flex-col sm:flex-row flex-col sm:flex-row ">
            <a href="/blogs">
                <li class="mx-2"><i class="fa fa-home mr-2"></i> Home</li>
            </a>
            <a href="/blogs/myblogs">
                <li class="mx-2"><i class="fa fa-box mr-2"></i> my Blogs</li>
            </a>
            <a href="#" class="font-bold">
                <li class="mx-2"><i class="fa fa-edit mr-2"></i> make a Blog</li>
            </a>
        </ul>
        <ul class="navbar  list-none flex justify-end items-center">
            <?php
            if ($session->get('user')) {
            ?>
                <!-- if user is logged in  -->
                <a href="/auth/logout">
                    <li class="mx-2"><i class="fa fa-lock mr-2"></i> Logout</li>
                </a>
            <?php
            } else {
            ?>
                <!-- if user is not logged in  -->
                <a href="/auth/">
                    <li class="mx-2"><i class="fa fa-lock mr-2"></i> Login</li>
                </a>
            <?php
            }
            ?>
        </ul>
        <div class="flex items-center justify-between sm:hidden">
            <i class="toggleNav fa fa-align-center cursor-pointer block"></i>
            <p class="text-white font-bold">Blogs</p>
        </div>
    </div>
</nav>
<div class="h-screen w-screen flex justify-center items-center">
    <form action="/blogs/create" method="post" class="p-3 w-2/3 mt-5">
        <label for="image" class="mt-2">
            <p><i class="fa fa-image bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> image</p>
            <input type="text" name="image" id="image" placeholder="image" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="title" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> title</p>
            <input type="text" name="title" id="title" placeholder="title" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="tags" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> tags</p>
            <input type="text" name="tags" id="tags" placeholder="tags" class="w-full border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <label for="content" class="mt-2">
            <p><i class="fa fa-font bg-gradient-to-tl from-pink-500 to-yellow-600 via-red-600 bg-clip-text text-transparent"></i> content</p>
            <textarea rows="10" name="content" id="content" placeholder="content" class="border-2 border-stone-700 rounded-sm mt-2 w-full" required>
        </textarea>
        </label>
        <label for="submit" class="w-full my-4">
            <input type="submit" value="Create" name="submit" id="name" class="w-full p-2 rounded-sm shadow-md cursor-pointer text-white bg-gradient-to-r from-pink-500 to-red-600 ">
        </label>
    </form>
</div>


<script>
    $(".toggleNav").click(function(e) {
        e.preventDefault();
        $(".navbar").toggleClass('hidden');
    });
</script>